---
# Path to file in which to store console allocations.
console_allocation_filename:

# Name or UUID of Ironic node to allocate a console for.
console_allocation_ironic_node:

# allocation_pool_start: First TCP port in the allocation pool
console_allocation_pool_start:

# allocation_pool_end: Last TCP port in the allocation pool
console_allocation_pool_end:
